from distutils.core import setup
setup(
  name = 'MoneyLover-Excel-Lib',
  packages = ['MoneyLover-Excel-Lib'], # this must be the same as the name above
  version = '0.5',
  description = 'A library to data crunch excel documents generated by the MoneyLover Android app',
  author = 'Tim Nibert',
  author_email = 'tmnibert@gmail.com',
  url = 'https://github.com/tnibert/MoneyLover-Excel-Lib', # use the URL to the github repo
  download_url = 'https://github.com/tnibert/MoneyLover-Excel-Lib/tarball/0.5', # I'll explain this in a second
  keywords = ['MoneyLover', 'budget', 'finance', 'analysis'], # arbitrary keywords
  classifiers = [],
)

